import { parseA1Groups } from './raw-types';

const SOURCE = `lexical.personal_detail_labels	lesson_candidate.locate_written_personal_details	lexical_set	name¦first name¦last name¦age¦address¦phone number¦email address¦date of birth¦nationality	الاسم¦الاسم الأول¦اسم العائلة¦العمر¦العنوان¦رقم الهاتف¦عنوان البريد الإلكتروني¦تاريخ الميلاد¦الجنسية
lexical.identity_place_labels	lesson_candidate.understand_spoken_personal_introductions	lexical_set	country¦city¦town¦street¦road¦home¦house¦flat¦address	بلد¦مدينة¦بلدة¦شارع¦طريق¦منزل¦بيت¦شقة¦عنوان
lexical.basic_people	lesson_candidate.understand_talk_about_people_and_family	lexical_set	person¦people¦man¦woman¦boy¦girl¦adult¦child¦children	شخص¦أشخاص / الناس¦رجل¦امرأة¦ولد¦بنت¦بالغ¦طفل¦أطفال
lexical.family_core	lesson_candidate.understand_talk_about_people_and_family	lexical_set	family¦parent¦mother¦father¦brother¦sister¦husband¦wife¦son¦daughter¦child¦children	عائلة¦والد / والدة¦أم¦أب¦أخ¦أخت¦زوج¦زوجة¦ابن¦ابنة¦طفل¦أطفال
lexical.known_people_roles	lesson_candidate.introduce_another_person	lexical_set	friend¦best friend¦neighbour¦classmate¦teacher¦student¦customer	صديق¦أفضل صديق¦جار¦زميل دراسة¦معلّم¦طالب¦عميل / زبون
lexical.familiar_jobs	lesson_candidate.introduce_another_person	lexical_set	job¦teacher¦doctor¦nurse¦driver¦manager¦worker¦waiter¦cook¦police officer	وظيفة¦معلّم¦طبيب¦ممرّض / ممرّضة¦سائق¦مدير¦عامل¦نادل¦طباخ¦ضابط شرطة
lexical.own_country_nationality	lesson_candidate.give_short_self_introduction	personalized_slot	the learner's country name¦the learner's nationality adjective¦one locally relevant comparison pair	اسم بلدك¦صفة جنسيتك¦زوج مقارنة مناسب لبيئتك
lexical.numbers_zero_to_hundred	lesson_candidate.understand_spoken_contact_details	lexical_set	zero-ten¦eleven-nineteen¦twenty, thirty, forty, fifty, sixty, seventy, eighty, ninety¦composed numbers 21-99¦one hundred	الأعداد من صفر إلى عشرة¦الأعداد من أحد عشر إلى تسعة عشر¦العشرات من عشرين إلى تسعين¦الأعداد المركبة من 21 إلى 99¦مئة
lexical.days_of_week	lesson_candidate.identify_spoken_time_and_date_details	lexical_set	Monday¦Tuesday¦Wednesday¦Thursday¦Friday¦Saturday¦Sunday	الاثنين¦الثلاثاء¦الأربعاء¦الخميس¦الجمعة¦السبت¦الأحد
lexical.months	lesson_candidate.identify_spoken_time_and_date_details	lexical_set	January¦February¦March¦April¦May¦June¦July¦August¦September¦October¦November¦December	يناير¦فبراير¦مارس¦أبريل¦مايو¦يونيو¦يوليو¦أغسطس¦سبتمبر¦أكتوبر¦نوفمبر¦ديسمبر
lexical.clock_calendar_words	lesson_candidate.identify_spoken_time_and_date_details	lexical_set	time¦clock¦hour¦minute¦o'clock¦quarter¦half¦date¦day¦week¦month¦year	وقت¦ساعة حائط / ساعة¦ساعة (مدة)¦دقيقة¦تمام الساعة¦ربع¦نصف¦تاريخ¦يوم¦أسبوع¦شهر¦سنة
lexical.ordinal_dates	lesson_candidate.identify_spoken_time_and_date_details	lexical_set	first¦second¦third¦fourth¦fifth¦sixth-twentieth¦twenty-first to thirty-first	الأول¦الثاني¦الثالث¦الرابع¦الخامس¦من السادس إلى العشرين¦من الحادي والعشرين إلى الحادي والثلاثين
lexical.relative_time_words	lesson_candidate.understand_a_simple_meeting_arrangement	lexical_set	now¦today¦tonight¦tomorrow¦yesterday¦morning¦afternoon¦evening¦night¦early¦late¦later¦soon	الآن¦اليوم¦الليلة¦غدًا¦أمس¦الصباح¦بعد الظهر¦المساء¦الليل¦مبكر¦متأخر¦لاحقًا¦قريبًا
lexical.core_daily_actions	lesson_candidate.understand_a_short_everyday_activity_text	lexical_set	wake up¦get up¦wash¦get dressed¦eat¦drink¦go¦come¦start¦finish¦sleep	يستيقظ¦ينهض¦يغسل / يغتسل¦يرتدي ملابسه¦يأكل¦يشرب¦يذهب¦يأتي¦يبدأ¦ينهي¦ينام
lexical.meals_and_routine	lesson_candidate.understand_a_short_everyday_activity_text	lexical_set	breakfast¦lunch¦dinner¦meal¦have breakfast¦have lunch¦have dinner	الإفطار¦الغداء¦العشاء¦وجبة¦يتناول الإفطار¦يتناول الغداء¦يتناول العشاء
lexical.work_and_study_actions	lesson_candidate.understand_a_short_everyday_activity_text	lexical_set	work¦study¦learn¦read¦write¦listen¦speak¦ask¦answer¦practise¦class¦lesson¦homework	يعمل¦يدرس¦يتعلم¦يقرأ¦يكتب¦يستمع¦يتحدث¦يسأل¦يجيب¦يتدرّب¦فصل / حصة¦درس¦واجب منزلي
lexical.home_routine_actions	lesson_candidate.understand_a_short_everyday_activity_text	lexical_set	cook¦clean¦shop¦buy¦make¦open¦close¦help¦call¦wait	يطبخ¦ينظّف¦يتسوّق¦يشتري¦يصنع¦يفتح¦يغلق¦يساعد¦يتصل¦ينتظر
lexical.leisure_core	lesson_candidate.understand_talk_about_leisure_preferences_and_abilities	lexical_set	read a book¦watch TV¦watch a film¦listen to music¦go to the cinema¦play a game¦walk¦dance¦take photos	يقرأ كتابًا¦يشاهد التلفاز¦يشاهد فيلمًا¦يستمع إلى الموسيقى¦يذهب إلى السينما¦يلعب لعبة¦يمشي¦يرقص¦يلتقط صورًا
lexical.sports_core	lesson_candidate.understand_talk_about_leisure_preferences_and_abilities	lexical_set	sport¦football¦tennis¦swimming¦running¦walking¦gym¦play football¦play tennis¦go swimming	رياضة¦كرة القدم¦التنس¦السباحة¦الجري¦المشي¦صالة رياضية¦يلعب كرة القدم¦يلعب التنس¦يذهب للسباحة
lexical.media_and_hobbies	lesson_candidate.understand_talk_about_leisure_preferences_and_abilities	lexical_set	music¦book¦film¦TV¦radio¦photo¦picture¦game¦computer game¦hobby	موسيقى¦كتاب¦فيلم¦تلفاز¦راديو¦صورة فوتوغرافية¦صورة¦لعبة¦لعبة كمبيوتر¦هواية
lexical.preference_evaluation_core	lesson_candidate.give_a_simple_leisure_profile	lexical_set	like¦love¦want¦need¦favourite¦good¦bad¦nice¦great¦interesting¦boring¦delicious¦fun¦easy¦difficult	يحب¦يعشق / يحب جدًا¦يريد¦يحتاج¦المفضّل¦جيد¦سيئ¦لطيف / جميل¦رائع¦ممتع / مثير للاهتمام¦ممل¦لذيذ¦مرح / ممتع¦سهل¦صعب
lexical.weather_core	lesson_candidate.describe_common_weather	lexical_set	weather¦sun¦rain¦snow¦wind¦sunny¦rainy¦cloudy¦windy¦hot¦warm¦cold	الطقس¦الشمس¦المطر¦الثلج¦الرياح¦مشمس¦ممطر¦غائم¦عاصف / كثير الرياح¦حار¦دافئ¦بارد
lexical.simple_sequence_words	lesson_candidate.follow_simple_game_or_activity_instructions	lexical_set	action¦activity¦routine¦first¦then¦next¦after¦before¦again¦always¦sometimes¦every day	فعل / إجراء¦نشاط¦روتين¦أولًا¦ثم¦التالي¦بعد¦قبل¦مرة أخرى¦دائمًا¦أحيانًا¦كل يوم
lexical.basic_colours	lesson_candidate.match_visual_descriptions_to_familiar_things	lexical_set	black¦white¦red¦blue¦green¦yellow¦brown¦orange¦pink¦grey	أسود¦أبيض¦أحمر¦أزرق¦أخضر¦أصفر¦بني¦برتقالي¦وردي¦رمادي
lexical.size_shape_age	lesson_candidate.match_visual_descriptions_to_familiar_things	lexical_set	big¦small¦large¦long¦short¦tall¦round¦square¦old¦new¦young	كبير¦صغير¦كبير / واسع¦طويل¦قصير¦طويل القامة¦دائري¦مربع¦قديم / مسن¦جديد¦صغير السن
lexical.appearance_condition	lesson_candidate.identify_familiar_referents_from_spoken_clues	lexical_set	beautiful¦clean¦dirty¦light¦dark¦open¦closed¦right¦wrong¦same¦different	جميل¦نظيف¦متسخ¦فاتح / خفيف¦داكن / مظلم¦مفتوح¦مغلق¦صحيح¦خطأ¦نفسه / مماثل¦مختلف
lexical.personal_everyday_objects	lesson_candidate.match_visual_descriptions_to_familiar_things	lexical_set	phone¦bag¦book¦pen¦pencil¦key¦money¦card¦ticket¦passport¦bottle¦cup¦glass¦box	هاتف¦حقيبة¦كتاب¦قلم¦قلم رصاص¦مفتاح¦مال¦بطاقة¦تذكرة¦جواز سفر¦زجاجة¦كوب¦كأس / كوب زجاجي¦صندوق
lexical.digital_objects	lesson_candidate.complete_a_very_simple_online_purchase_or_application	lexical_set	computer¦laptop¦phone¦screen¦camera¦internet¦website¦email¦password	كمبيوتر¦حاسوب محمول¦هاتف¦شاشة¦كاميرا¦الإنترنت¦موقع إلكتروني¦بريد إلكتروني¦كلمة مرور
lexical.home_types_rooms	lesson_candidate.exchange_basic_information_about_a_home	lexical_set	home¦house¦flat¦apartment¦room¦bedroom¦bathroom¦kitchen¦living room¦dining room¦garden	منزل¦بيت¦شقة¦شقة¦غرفة¦غرفة نوم¦حمّام¦مطبخ¦غرفة معيشة¦غرفة طعام¦حديقة
lexical.home_furniture_features	lesson_candidate.exchange_basic_information_about_a_home	lexical_set	bed¦chair¦table¦sofa¦desk¦door¦window¦wall¦floor¦shower¦bath¦television	سرير¦كرسي¦طاولة¦أريكة¦مكتب¦باب¦نافذة¦حائط¦أرضية¦دُش¦حوض استحمام¦تلفاز
lexical.pets_animals	lesson_candidate.write_simple_people_profile_cards	lexical_set	animal¦pet¦dog¦cat¦bird¦fish¦horse	حيوان¦حيوان أليف¦كلب¦قطة¦طائر¦سمكة¦حصان`;

export const A1_CORE_GROUPS = parseA1Groups(SOURCE);
