import { parseA1Groups } from './raw-types';

const SOURCE = `lexical.self_introduction_frames	lesson_candidate.give_short_self_introduction	frame_set	Hello. My name is ...¦I'm ...¦I'm from ...¦I live in ...¦I'm a/an ...¦I like ...	مرحبًا. اسمي ...¦أنا ...¦أنا من ...¦أنا أعيش في ...¦أنا ... (مهنة)¦أنا أحب ...
lexical.personal_question_frames	lesson_candidate.exchange_personal_details_orally	frame_set	What's your name?¦Where are you from?¦Where do you live?¦What's your job?¦How old are you?¦What's your phone number?	ما اسمك؟¦من أين أنت؟¦أين تعيش؟¦ما وظيفتك؟¦كم عمرك؟¦ما رقم هاتفك؟
lexical.contact_repair_frames	lesson_candidate.understand_spoken_contact_details	frame_set	Can you spell that?¦Capital or small letter?¦Please say that again.¦Is that ...?¦Yes, that's right.¦No, it's ...	هل يمكنك تهجئة ذلك؟¦حرف كبير أم صغير؟¦من فضلك قل ذلك مرة أخرى.¦هل هو ...؟¦نعم، هذا صحيح.¦لا، إنه ...
lexical.other_person_introduction	lesson_candidate.introduce_another_person	frame_set	This is ...¦This is my ...¦He's/She's a/an ...¦Nice to meet you.¦Nice to meet you too.	هذا / هذه ...¦هذا / هذه ... لي¦هو/هي ... (مهنة)¦سعيد بلقائك.¦وأنا أيضًا سعيد بلقائك.
lexical.family_profile_frames	lesson_candidate.exchange_information_about_family_and_friends	frame_set	This is my ...¦I have ...¦His/Her name is ...¦He/She is ...¦He/She has ...	هذا / هذه ... لي¦لدي ...¦اسمه/اسمها ...¦هو/هي ...¦لديه/لديها ...
lexical.friend_message_frames	lesson_candidate.write_a_short_message_to_a_friend	frame_set	Hi ...¦How are you?¦I'm ...¦Can you ...?¦See you soon.¦Bye for now.	مرحبًا ...¦كيف حالك؟¦أنا ...¦هل يمكنك ...؟¦أراك قريبًا.¦إلى اللقاء الآن.
lexical.greeting_wellbeing_closing	lesson_candidate.open_and_close_a_basic_social_exchange	frame_set	Hello/Hi.¦Good morning/afternoon/evening.¦How are you?¦I'm fine, thanks.¦Goodbye/Bye.¦See you soon.	مرحبًا / أهلًا.¦صباح الخير / مساء الخير.¦كيف حالك؟¦أنا بخير، شكرًا.¦مع السلامة / إلى اللقاء.¦أراك قريبًا.
lexical.basic_polite_forms	lesson_candidate.use_basic_everyday_polite_forms	frame_set	Please.¦Thank you/Thanks.¦You're welcome.¦Sorry.¦Excuse me.	من فضلك.¦شكرًا لك / شكرًا.¦العفو.¦آسف.¦عذرًا / لو سمحت.
lexical.accept_agree_decline	lesson_candidate.agree_to_a_simple_request	frame_set	Yes, of course.¦Sure.¦Okay.¦Yes, please.¦No, thank you.¦Sorry, I can't.	نعم، بالطبع.¦بالتأكيد.¦حسنًا.¦نعم، من فضلك.¦لا، شكرًا.¦آسف، لا أستطيع.
lexical.sympathy_interest_reactions	lesson_candidate.show_basic_sympathy_during_a_problem_or_disagreement	frame_set	Oh no.¦I'm sorry.¦I'm sorry to hear that.¦That's great.¦Good idea.¦I like that.	يا للأسف.¦أنا آسف.¦آسف لسماع ذلك.¦هذا رائع.¦فكرة جيدة.¦أحب ذلك.
lexical.meeting_arrangement_frames	lesson_candidate.understand_a_simple_meeting_arrangement	frame_set	Let's meet at ...¦Can you come on ...?¦Meet me at ...¦See you at ...¦I'm sorry, I can't.	لنتقابل الساعة / في ...¦هل يمكنك الحضور يوم ...؟¦قابلني عند / في ...¦أراك عند / الساعة ...¦أنا آسف، لا أستطيع.
lexical.date_time_frames	lesson_candidate.identify_spoken_time_and_date_details	frame_set	It's on Monday.¦It's on 12 May.¦It's at three o'clock.¦It's at half past three.¦It's at quarter past/to three.	إنه يوم الاثنين.¦إنه في 12 مايو.¦إنه الساعة الثالثة تمامًا.¦إنه الثالثة والنصف.¦إنه الثالثة والربع / إلا ربعًا.
lexical.routine_sequence_frames	lesson_candidate.describe_a_simple_everyday_routine	frame_set	Every day, I ...¦In the morning/afternoon/evening, I ...¦I ... at ...¦First, I ...¦Then, I ...¦After that, I ...	كل يوم، أنا ...¦في الصباح / بعد الظهر / المساء، أنا ...¦أنا ... الساعة ...¦أولًا، أنا ...¦ثم، أنا ...¦بعد ذلك، أنا ...
lexical.preference_ability_frames	lesson_candidate.understand_talk_about_leisure_preferences_and_abilities	frame_set	I like/love ...¦I don't like ...¦My favourite ... is ...¦I can ...¦I can't ...¦Do you like ...?¦Can you ...?	أنا أحب / أعشق ...¦أنا لا أحب ...¦المفضّل لدي هو ...¦أستطيع ...¦لا أستطيع ...¦هل تحب ...؟¦هل تستطيع ...؟
lexical.weather_frames	lesson_candidate.describe_common_weather	frame_set	It's hot/cold/warm.¦It's sunny/rainy/cloudy/windy.¦It's raining/snowing.	الجو حار / بارد / دافئ.¦الجو مشمس / ممطر / غائم / عاصف.¦إنها تمطر / تثلج.
lexical.object_description_frames	lesson_candidate.describe_a_familiar_object_orally	frame_set	It's a/an ...¦It's [colour].¦It's big/small/long/short.¦It has ...¦This one is ...	إنه / إنها ...¦لونه ...¦إنه كبير / صغير / طويل / قصير.¦لديه / به ...¦هذا واحد ...
lexical.object_information_gap	lesson_candidate.identify_familiar_referents_from_spoken_clues	frame_set	What is it?¦What colour is it?¦Is it big or small?¦How many ... are there?¦There is/are ...	ما هذا؟¦ما لونه؟¦هل هو كبير أم صغير؟¦كم ... يوجد؟¦يوجد / توجد ...
lexical.home_presence_frames	lesson_candidate.exchange_basic_information_about_a_home	frame_set	There is a/an ...¦There are ...¦There isn't/aren't ...¦Is there ...?¦Are there ...?¦Do you have ...?	يوجد ...¦توجد / يوجد ...¦لا يوجد / لا توجد ...¦هل يوجد ...؟¦هل توجد / يوجد ...؟¦هل لديك ...؟
lexical.location_frames	lesson_candidate.describe_people_and_object_locations_orally	frame_set	It's in/on/under ...¦It's next to/opposite ...¦He's/She's at/in ...¦It's here/there.¦Where is/are ...?	إنه في / على / تحت ...¦إنه بجوار / مقابل ...¦هو/هي عند / في ...¦إنه هنا / هناك.¦أين ...؟
lexical.wayfinding_frames	lesson_candidate.follow_simple_written_wayfinding_directions	frame_set	Excuse me, where is ...?¦How do I get to ...?¦Go straight.¦Turn left/right.¦It's next to/opposite ...¦It's on your left/right.	عذرًا، أين ...؟¦كيف أصل إلى ...؟¦اذهب مباشرة.¦انعطف يسارًا / يمينًا.¦إنه بجوار / مقابل ...¦إنه على يسارك / يمينك.
lexical.live_direction_repair	lesson_candidate.follow_simple_directions_from_an_interlocutor	frame_set	This way?¦Left or right?¦Is that right?¦Please say that again.¦Okay, thank you.	من هذا الطريق؟¦يسار أم يمين؟¦هل هذا صحيح؟¦من فضلك قل ذلك مرة أخرى.¦حسنًا، شكرًا لك.`;

export const A1_FRAMES_A_GROUPS = parseA1Groups(SOURCE);
