import { parseA1Groups } from './raw-types';

const SOURCE = `lexical.immediate_place_referents	lesson_candidate.describe_people_and_object_locations_orally	lexical_set	place¦building¦room¦door¦window¦table¦chair¦person¦thing¦here¦there	مكان¦مبنى¦غرفة¦باب¦نافذة¦طاولة¦كرسي¦شخص¦شيء¦هنا¦هناك
lexical.position_route_words	lesson_candidate.understand_where_things_or_people_are	lexical_set	left¦right¦straight¦near¦far¦inside¦outside¦front¦back¦under¦behind¦between¦next to¦opposite	يسار¦يمين¦مباشرة / مستقيم¦قريب¦بعيد¦بالداخل¦بالخارج¦الأمام¦الخلف¦تحت¦خلف¦بين¦بجوار¦مقابل
lexical.public_place_labels	lesson_candidate.understand_simple_place_and_hotel_information	lexical_set	school¦college¦office¦shop¦supermarket¦restaurant¦cafe¦hotel¦station¦airport¦hospital¦bank¦post office¦toilet¦park	مدرسة¦كلية¦مكتب¦متجر¦سوبرماركت¦مطعم¦مقهى¦فندق¦محطة¦مطار¦مستشفى¦بنك¦مكتب بريد¦دورة مياه¦حديقة عامة
lexical.route_actions	lesson_candidate.follow_simple_written_wayfinding_directions	lexical_set	go¦come¦walk¦turn¦cross¦stop¦start¦follow¦take¦get on¦get off	يذهب¦يأتي¦يمشي¦ينعطف¦يعبر¦يتوقف¦يبدأ¦يتبع¦يأخذ¦يركب¦ينزل
lexical.transport_core	lesson_candidate.follow_slow_spoken_route_directions	lexical_set	bus¦train¦taxi¦car¦plane¦bicycle¦station¦airport¦bus stop¦platform	حافلة / أتوبيس¦قطار¦سيارة أجرة / تاكسي¦سيارة¦طائرة¦دراجة¦محطة¦مطار¦موقف الحافلة¦رصيف المحطة
lexical.ticket_details	lesson_candidate.buy_a_basic_public_transport_ticket	lexical_set	ticket¦single¦return¦one way¦adult¦child¦to¦from¦today¦tomorrow	تذكرة¦ذهاب فقط¦ذهاب وعودة¦اتجاه واحد¦بالغ¦طفل¦إلى¦من¦اليوم¦غدًا
lexical.hotel_core	lesson_candidate.check_in_at_a_hotel	lexical_set	hotel¦booking¦room¦name¦passport¦key¦night¦breakfast¦reception¦check-in¦check-out	فندق¦حجز¦غرفة¦اسم¦جواز سفر¦مفتاح¦ليلة¦إفطار¦الاستقبال¦تسجيل الدخول¦تسجيل الخروج
lexical.money_price	lesson_candidate.identify_a_price_in_slow_spoken_service_information	lexical_set	money¦price¦cost¦bill¦cash¦card¦pound¦dollar¦euro¦cheap¦expensive¦free¦total	مال¦سعر¦تكلفة / يكلّف¦فاتورة¦نقدًا / كاش¦بطاقة¦جنيه¦دولار¦يورو¦رخيص¦غالي¦مجاني¦الإجمالي
lexical.shopping_options	lesson_candidate.follow_a_slow_everyday_service_exchange	lexical_set	buy¦pay¦shop¦size¦small¦medium¦large¦colour¦one¦two¦more¦other	يشتري¦يدفع¦متجر / يتسوّق¦مقاس¦صغير¦متوسط¦كبير¦لون¦واحد¦اثنان¦المزيد¦آخر
lexical.food_drink_core	lesson_candidate.ask_for_basic_food_or_drink	lexical_set	food¦drink¦menu¦order¦water¦tea¦coffee¦milk¦juice¦bread¦rice¦chicken¦meat¦fish¦egg¦fruit¦vegetable	طعام¦شراب¦قائمة الطعام¦طلب / يطلب¦ماء¦شاي¦قهوة¦حليب¦عصير¦خبز¦أرز¦دجاج¦لحم¦سمك¦بيضة¦فاكهة¦خضروات
lexical.simple_food_options	lesson_candidate.state_a_basic_food_or_drink_preference	lexical_set	apple¦banana¦orange¦sandwich¦salad¦soup¦cake¦sugar¦salt¦hot¦cold	تفاحة¦موزة¦برتقالة¦ساندويتش¦سلطة¦شوربة¦كعكة¦سكر¦ملح¦ساخن¦بارد
lexical.quantity_containers	lesson_candidate.exchange_visible_object_information	lexical_set	one¦two¦some¦more¦all¦bottle¦cup¦glass¦box¦bag¦piece¦kilo	واحد¦اثنان¦بعض¦المزيد¦الكل¦زجاجة¦كوب¦كأس / كوب زجاجي¦صندوق¦حقيبة¦قطعة¦كيلو
lexical.advertisement_details	lesson_candidate.find_key_details_in_a_simple_advertisement_or_leaflet	lexical_set	offer¦sale¦price¦date¦time¦place¦open¦closed¦free¦start¦finish¦departure	عرض¦تخفيضات / بيع¦سعر¦تاريخ¦وقت¦مكان¦مفتوح¦مغلق¦مجاني¦بداية / يبدأ¦نهاية / ينتهي¦مغادرة
lexical.service_need_words	lesson_candidate.follow_a_slow_everyday_service_exchange	lexical_set	help¦need¦want¦problem¦information¦please¦yes¦no¦okay¦sorry¦wait	مساعدة¦يحتاج¦يريد¦مشكلة¦معلومات¦من فضلك¦نعم¦لا¦حسنًا¦آسف¦انتظر
lexical.body_core	lesson_candidate.describe_a_simple_problem_to_a_health_professional	lexical_set	head¦face¦eye¦ear¦mouth¦tooth¦neck¦arm¦hand¦back¦stomach¦leg¦foot	رأس¦وجه¦عين¦أذن¦فم¦سن¦رقبة¦ذراع¦يد¦ظهر¦معدة / بطن¦ساق¦قدم
lexical.health_states	lesson_candidate.describe_a_simple_problem_to_a_health_professional	lexical_set	well¦ill¦sick¦pain¦hurt¦tired¦cold¦hot¦problem¦doctor¦hospital¦medicine	بخير¦مريض¦مريض / أشعر بالغثيان¦ألم¦يؤلم¦متعب¦برد / زكام¦حر / حار¦مشكلة¦طبيب¦مستشفى¦دواء
lexical.form_digital_actions	lesson_candidate.complete_a_very_simple_online_purchase_or_application	lexical_set	form¦enter¦write¦choose¦select¦click¦open¦close¦send¦buy¦pay¦check¦complete	نموذج¦أدخل¦اكتب¦اختر¦حدّد¦انقر¦افتح¦أغلق¦أرسل¦اشترِ¦ادفع¦تحقق¦أكمل
lexical.form_fields	lesson_candidate.complete_a_simple_information_form	lexical_set	first name¦last name¦address¦email¦phone number¦date¦country¦nationality¦password¦card number	الاسم الأول¦اسم العائلة¦العنوان¦البريد الإلكتروني¦رقم الهاتف¦التاريخ¦البلد¦الجنسية¦كلمة المرور¦رقم البطاقة
lexical.public_notice_words	lesson_candidate.understand_common_signs_notices_and_visual_instructions	lexical_set	open¦closed¦stop¦exit¦entrance¦information¦toilet¦danger¦no smoking¦no entry¦keep left	مفتوح¦مغلق¦توقف¦مخرج¦مدخل¦معلومات¦دورة مياه¦خطر¦ممنوع التدخين¦ممنوع الدخول¦الزم اليسار
lexical.basic_feelings	lesson_candidate.open_and_close_a_basic_social_exchange	lexical_set	happy¦sad¦tired¦hungry¦thirsty¦worried¦afraid¦sorry¦fine¦okay¦great	سعيد¦حزين¦متعب¦جائع¦عطشان¦قلق¦خائف¦آسف¦بخير¦حسنًا¦رائع
lexical.news_media_topics	lesson_candidate.identify_a_headline_news_topic_from_visual_media	lexical_set	news¦video¦topic¦weather¦sport¦people¦place¦travel¦food¦music¦film¦product¦story	أخبار¦فيديو¦موضوع¦طقس¦رياضة¦أشخاص / الناس¦مكان¦سفر¦طعام¦موسيقى¦فيلم¦منتج¦قصة
lexical.core_story_actions	lesson_candidate.understand_outline_of_an_illustrated_short_story	lexical_set	go¦come¦see¦meet¦say¦tell¦give¦take¦find¦lose¦make¦get¦have¦start¦finish	يذهب¦يأتي¦يرى¦يقابل¦يقول¦يخبر¦يعطي¦يأخذ¦يجد¦يفقد¦يصنع¦يحصل على¦لديه¦يبدأ¦ينهي
lexical.task_instruction_actions	lesson_candidate.follow_short_written_everyday_instructions	lexical_set	read¦write¦listen¦speak¦look¦match¦choose¦circle¦complete¦answer¦ask¦check¦repeat¦open¦close¦true¦false	اقرأ¦اكتب¦استمع¦تحدث¦انظر¦طابق¦اختر¦ضع دائرة¦أكمل¦أجب¦اسأل¦تحقق¦كرّر¦افتح¦أغلق¦صحيح¦خطأ
lexical.dictionary_meaning_words	lesson_candidate.translate_simple_written_phrases_with_a_dictionary	lexical_set	word¦phrase¦meaning¦example¦dictionary¦English¦Arabic¦same¦different¦choose¦check	كلمة¦عبارة¦معنى¦مثال¦قاموس¦الإنجليزية¦العربية¦نفس / مماثل¦مختلف¦اختر¦تحقق
lexical.extended_family_life	lesson_candidate.understand_talk_about_people_and_family	lexical_set	aunt¦uncle¦cousin¦grandfather¦grandmother¦grandparent¦partner¦boyfriend¦girlfriend¦married¦born¦birthday	عمة / خالة¦عم / خال¦ابن/ابنة العم أو الخال¦جد¦جدة¦أحد الأجداد¦شريك¦حبيب¦حبيبة¦متزوج¦وُلد¦عيد ميلاد
lexical.people_appearance_manner	lesson_candidate.understand_talk_about_people_and_family	lexical_set	hair¦blonde¦friendly¦quiet¦busy¦funny¦nice¦young¦old¦tall¦short	شعر¦أشقر¦ودود¦هادئ¦مشغول¦مضحك¦لطيف¦صغير السن¦كبير السن¦طويل القامة¦قصير القامة
lexical.clothing_core	lesson_candidate.match_visual_descriptions_to_familiar_things	lexical_set	clothes¦coat¦hat¦jacket¦jeans¦shirt¦shoe¦skirt¦sweater¦trousers¦T-shirt	ملابس¦معطف¦قبعة¦سترة¦جينز¦قميص¦حذاء¦تنورة¦كنزة / سويتر¦بنطال¦تي شيرت
lexical.events_seasons	lesson_candidate.understand_a_simple_meeting_arrangement	lexical_set	birthday¦party¦meeting¦weekend¦holiday¦concert¦festival¦event¦spring¦summer¦autumn¦winter	عيد ميلاد¦حفلة¦اجتماع / موعد¦عطلة نهاية الأسبوع¦إجازة / عطلة¦حفلة موسيقية¦مهرجان¦فعالية / حدث¦الربيع¦الصيف¦الخريف¦الشتاء
lexical.familiar_places_extended	lesson_candidate.understand_outline_of_a_simple_guided_tour	lexical_set	area¦beach¦centre¦farm¦island¦library¦market¦museum¦river¦sea¦village	منطقة¦شاطئ¦مركز¦مزرعة¦جزيرة¦مكتبة¦سوق¦متحف¦نهر¦بحر¦قرية
lexical.journey_detail_words	lesson_candidate.follow_simple_written_wayfinding_directions	lexical_set	map¦journey¦trip¦flight¦tourist¦traffic¦arrive¦leave¦travel	خريطة¦رحلة¦رحلة / نزهة¦رحلة جوية¦سائح¦حركة المرور¦يصل¦يغادر¦يسافر / سفر
lexical.communication_text_nouns	lesson_candidate.write_a_short_message_to_a_friend	lexical_set	conversation¦language¦letter¦message¦note¦page¦question¦sentence¦spelling¦text¦word¦phrase¦list	محادثة¦لغة¦خطاب / رسالة¦رسالة¦ملاحظة¦صفحة¦سؤال¦جملة¦تهجئة¦نص¦كلمة¦عبارة¦قائمة
lexical.high_utility_action_extension	lesson_candidate.understand_a_short_everyday_activity_text	lexical_set	arrive¦bring¦carry¦drive¦put¦sit¦stand¦stay¦visit¦wear¦use¦try	يصل¦يحضر¦يحمل¦يقود¦يضع¦يجلس¦يقف¦يبقى¦يزور¦يرتدي¦يستخدم¦يجرّب`;

export const A1_PRACTICAL_GROUPS = parseA1Groups(SOURCE);
